name: math_modeling
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- pip
- ipykernel
- numpy
- pandas
- scikit-learn
- matplotlib
- openpyxl
- xlrd
- pyyaml
- requests
- python-dotenv
- jsonschema
- bibtexparser
- conda-lock
- pip:
  - opencv-python==4.13.0.92
